<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Dashboard extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_logged_in();

        $this->load->model('Tb_st_model');
        $this->load->model('Tb_spd_model');
    }

    function index()
    {

        $data['title'] = "Perjadin";
        $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();

        $id = $this->session->userdata('id');
        $data['tb_st'] = $this->Tb_st_model->get_all_tb_st($id);
        $data['tb_spd'] = $this->Tb_spd_model->get_all_tb_spd($id);

        $this->load->view('template1/header', $data);
        $this->load->view('template1/sidebar');
        $this->load->view('template1/topbar', $data);
        $this->load->view('menu/index', $data);
        $this->load->view('template1/footer');
    }
}
        








// where()
// This function enables you to set WHERE clauses in your query.

// You can also add where clauses, sort conditions and so forth:

// $this->db->select('first_name', 'last_name');
// $this->db->from('people');
// $this->db->where('id', 449587);
// $this->db->order_by('last_name, first_name');
// $query = $this->db->get();
// It’s possible to chain all these conditions together on a single line, but I prefer putting them on separate lines for readability.

// In simple word, get_where is a luxury to use but where() gives you more flexibility to use.
