<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Tb_instansi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_logged_in();
        $this->load->model('Tb_instansi_model');
    }

    /*
     * Listing of tb_instansi
     */
    function index()
    {
        $id = $this->session->userdata('id');
        $data['tb_instansi'] = $this->Tb_instansi_model->get_all_tb_instansi($id);
        $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();

        $data['title'] = "Perjadin";
        $this->load->view('template1/header', $data);
        $this->load->view('template1/sidebar');
        $this->load->view('template1/topbar');
        $this->load->view('tb_instansi/index', $data);
        $this->load->view('template1/footer');
    }

    /*
     * Adding a new tb_instansi
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('nm_instansi', 'Nm Instansi', 'required');
        $this->form_validation->set_rules('nm_skpd', 'Nm Skpd', 'required');
        $this->form_validation->set_rules('alamat', 'Alamat', 'required');


        if ($this->form_validation->run()) {
            $nm_instansi = $this->input->post('nm_instansi');
            $nm_skpd = $this->input->post('nm_skpd');
            $alamat = $this->input->post('alamat');
            $gambar = 'logo.jpg';
            $id = $this->session->userdata('id');

            //  $upload_image = $_FILES['gambar'];

            // if ($upload_image) {
            //     $config['upload_path']          = './assets/foto';
            //     $config['allowed_types'] = 'gif|jpg|png';
            //     $config['max_size']      = '2048';

            //     $this->load->library('upload', $config);

            //     if ($this->upload->do_upload('gambar')) {
            //         $gambar = $this->upload->data('file_name');
            //     } else {
            //         echo $this->upload->dispay_errors();
            //     }
            // }

            $params = [
                'nm_instansi' => $nm_instansi,
                'nm_skpd' => $nm_skpd,
                'alamat' => $alamat,
                'gambar' => $gambar,
                'id' => $id
            ];
            $tb_instansi_id = $this->Tb_instansi_model->add_tb_instansi($params);
            redirect('tb_instansi/index');
        } else {
            $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();
            $data['title'] = "Perjadin";
            $this->load->view('template1/header', $data);
            $this->load->view('template1/sidebar');
            $this->load->view('template1/topbar');
            $this->load->view('tb_instansi/add', $data);
            $this->load->view('template1/footer');
        }
    }




    /*
     * Editing a tb_instansi
     */
    function edit($id_instansi)
    {

        // check if the tb_instansi exists before trying to edit it
        $data['tb_instansi'] = $this->Tb_instansi_model->get_tb_instansi($id_instansi);

        if (isset($data['tb_instansi']['id_instansi'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('nm_instansi', 'Nm Instansi', 'required');
            $this->form_validation->set_rules('nm_skpd', 'Nm Skpd', 'required');
            $this->form_validation->set_rules('alamat', 'Alamat', 'required');


            if ($this->form_validation->run()) {
                $nm_instansi = $this->input->post('nm_instansi');
                $nm_skpd = $this->input->post('nm_skpd');
                $alamat = $this->input->post('alamat');
                $gambar = $this->input->post('gambar');


                $upload_image = $_FILES['gambar'];

                if ($upload_image) {
                    $config['upload_path']          = './assets/foto';
                    $config['allowed_types'] = 'gif|jpg|png';
                    $config['max_size']      = '2048';

                    $this->load->library('upload', $config);

                    if ($this->upload->do_upload('gambar')) {
                        $old_image = $data['tb_instansi']['gambar'];
                        if ($old_image != 'logo.jpg') {
                            unlink(FCPATH . './assets/foto/' . $old_image);
                        }
                        $gambar = $this->upload->data('file_name');
                    } else {
                        echo $this->upload->dispay_errors();
                    }
                }


                $params = [
                    'nm_instansi' => $nm_instansi,
                    'nm_skpd' => $nm_skpd,
                    'alamat' => $alamat,
                    'gambar' => $gambar
                ];
                $this->Tb_instansi_model->update_tb_instansi($id_instansi, $params);
                redirect('tb_instansi/index');
            } else {
                $data['title'] = "Perjadin";
                $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();
                $this->load->view('template1/header', $data);
                $this->load->view('template1/sidebar');
                $this->load->view('template1/topbar');
                $this->load->view('tb_instansi/edit', $data);
                $this->load->view('template1/footer');
            }
        } else
            show_error('The tb_instansi you are trying to edit does not exist.');
    }

    /*
     * Deleting tb_instansi
     */
    function remove($id_instansi)
    {
        $tb_instansi = $this->Tb_instansi_model->get_tb_instansi($id_instansi);

        // check if the tb_instansi exists before trying to delete it
        if (isset($tb_instansi['id_instansi'])) {
            $this->Tb_instansi_model->delete_tb_instansi($id_instansi);
            redirect('tb_instansi/index');
        } else
            show_error('The tb_instansi you are trying to delete does not exist.');
    }
}
