<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Tb_st extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_logged_in();

        $this->load->model('Tb_st_model');
        $this->load->model('Tb_instansi_model');
        $this->load->model('Tb_ttd_model');
        $this->load->model('m_campur');
    }

    /*
     * Listing of tb_st
     */
    function index()
    {

        $id = $this->session->userdata('id');
        $data['tb_st'] = $this->Tb_st_model->get_all_tb_st($id);
        $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();

        $data['title'] = "Perjadin";
        $this->load->view('template1/header', $data);
        $this->load->view('template1/sidebar');
        $this->load->view('template1/topbar');
        $this->load->view('tb_st/index', $data);
        $this->load->view('template1/footer');
    }

    public function rekap()
    {
        // $this->load->model('Tb_st_model');
        // $this->load->model('Tb_spd_model');
        
        $data['title'] = "Rekap SPPD | Perjadin";
        $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();

        $id = $this->session->userdata('id');
        $data['rekapan'] = $this->m_campur->rekaptab($id);
        


        $data['title'] = "Rekap SPPD | Perjadin";
        $this->load->view('template1/header', $data);
        $this->load->view('template1/sidebar');
        $this->load->view('template1/topbar');
        $this->load->view('tb_st/rekapanmu', $data);
        $this->load->view('template1/footer');
    }

    /*
     * Adding a new tb_st
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('no_st', 'No St', 'required|min_length[8]');
        $this->form_validation->set_rules('tgl_surat', 'Tgl Surat', 'required');
        $this->form_validation->set_rules('dasar', 'Dasar', 'required');
        $this->form_validation->set_rules('maksud', 'Maksud', 'required');
        $this->form_validation->set_rules('t_berangkat', 'T Berangkat', 'required');
        $this->form_validation->set_rules('t_tujuan', 'T Tujuan', 'required');
        $this->form_validation->set_rules('tgl_berangkat', 'Tgl Berangkat', 'required');
        $this->form_validation->set_rules('tgl_kembali', 'Tgl Kembali', 'required');
        $this->form_validation->set_rules('alat_angkut', 'Alat Angkut', 'required');
        $this->form_validation->set_rules('id_instansi', 'SPKD Isi', 'required');
        $this->form_validation->set_rules('id_nip_ttd', 'Pejabat ttd Isi', 'required');




        if ($this->form_validation->run()) {
            $params = array(
                'no_st' => $this->input->post('no_st'),
                'tgl_surat' => $this->input->post('tgl_surat'),
                'dasar' => $this->input->post('dasar'),
                'maksud' => $this->input->post('maksud'),
                't_berangkat' => $this->input->post('t_berangkat'),
                't_tujuan' => $this->input->post('t_tujuan'),
                'tgl_berangkat' => $this->input->post('tgl_berangkat'),
                'tgl_kembali' => $this->input->post('tgl_kembali'),
                'alat_angkut' => $this->input->post('alat_angkut'),
                'id_instansi' => $this->input->post('id_instansi'),
                'id_nip_ttd' => $this->input->post('id_nip_ttd'),
                'id' => $this->session->userdata('id')


            );

            $tb_st_id = $this->Tb_st_model->add_tb_st($params);
            redirect('tb_st/index');
        } else {
            $id = $this->session->userdata('id');
            $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();


            $data['all_tb_ttd'] = $this->Tb_ttd_model->get_all_tb_ttd($id);
            $data['all_tb_instansi'] = $this->Tb_instansi_model->get_all_tb_instansi($id);


            $data['title'] = "Perjadin";
            $this->load->view('template1/header', $data);
            $this->load->view('template1/sidebar');
            $this->load->view('template1/topbar');
            $this->load->view('tb_st/add', $data);
            $this->load->view('template1/footer');
        }
    }

    /*
     * Editing a tb_st
     */
    function edit($id_st)
    {
        // check if the tb_st exists before trying to edit it
        $data['tb_st'] = $this->Tb_st_model->get_tb_st($id_st);

        if (isset($data['tb_st']['id_st'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('no_st', 'No St', 'required|min_length[8]');
            $this->form_validation->set_rules('tgl_surat', 'Tgl Surat', 'required');
            $this->form_validation->set_rules('dasar', 'Dasar', 'required');
            $this->form_validation->set_rules('maksud', 'Maksud', 'required');
            $this->form_validation->set_rules('t_berangkat', 'T Berangkat', 'required');
            $this->form_validation->set_rules('t_tujuan', 'T Tujuan', 'required');
            $this->form_validation->set_rules('tgl_berangkat', 'Tgl Berangkat', 'required');
            $this->form_validation->set_rules('tgl_kembali', 'Tgl Kembali', 'required');
            $this->form_validation->set_rules('alat_angkut', 'Alat Angkut', 'required');
            $this->form_validation->set_rules('id_instansi', 'SKPD Isi', 'required');
            $this->form_validation->set_rules('id_nip_ttd', 'Pejabat ttd Isi', 'required');



            if ($this->form_validation->run()) {
                $params = array(
                    'id_st' => $this->input->post('id_st'),
                    'no_st' => $this->input->post('no_st'),
                    'tgl_surat' => $this->input->post('tgl_surat'),
                    'dasar' => $this->input->post('dasar'),
                    'maksud' => $this->input->post('maksud'),
                    't_berangkat' => $this->input->post('t_berangkat'),
                    't_tujuan' => $this->input->post('t_tujuan'),
                    'tgl_berangkat' => $this->input->post('tgl_berangkat'),
                    'tgl_kembali' => $this->input->post('tgl_kembali'),
                    'alat_angkut' => $this->input->post('alat_angkut'),
                    'id_instansi' => $this->input->post('id_instansi'),
                    'id_nip_ttd' => $this->input->post('id_nip_ttd'),
                );

                $this->Tb_st_model->update_tb_st($id_st, $params);
                redirect('detail/detail_st/' . $params['id_st']);
            } else {
                $id = $this->session->userdata('id');
                $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();
                $data['all_tb_ttd'] = $this->Tb_ttd_model->get_all_tb_ttd($id);
                $data['all_tb_instansi'] = $this->Tb_instansi_model->get_all_tb_instansi($id);

                $data['title'] = "Perjadin";
                $this->load->view('template1/header', $data);
                $this->load->view('template1/sidebar');
                $this->load->view('template1/topbar');
                $this->load->view('tb_st/edit', $data);
                $this->load->view('template1/footer');
            }
        } else
            show_error('The tb_st you are trying to edit does not exist.');
    }

    /*
     * Deleting tb_st
     */
    function remove($id_st)
    {
        $tb_st = $this->Tb_st_model->get_tb_st($id_st);

        // check if the tb_st exists before trying to delete it
        if (isset($tb_st['id_st'])) {
            $this->Tb_st_model->delete_tb_st($id_st);
            redirect('tb_st/index');
        } else
            show_error('The tb_st you are trying to delete does not exist.');
    }




    function edit1($id_st)
    {
        // check if the tb_st exists before trying to edit it
        $data['tb_st'] = $this->Tb_st_model->get_tb_st($id_st);

        if (isset($data['tb_st']['id_st'])) {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('lap1', 'laporan1', 'min_length[4]');


            if ($this->form_validation->run()) {
                $params = array(
                    'id_st' => $this->input->post('id_st'),
                    'no_u1' => $this->input->post('no_u1'),
                    'no_u2' => $this->input->post('no_u2'),
                    'no_u3' => $this->input->post('no_u3'),
                    'no_u4' => $this->input->post('no_u4'),
                    'no_u5' => $this->input->post('no_u5'),
                    'lap1' => $this->input->post('lap1'),
                    'lap2' => $this->input->post('lap2'),
                    'lap3' => $this->input->post('lap3'),
                    'lap4' => $this->input->post('lap4'),
                    'lap5' => $this->input->post('lap5'),


                );

                $this->Tb_st_model->update_tb_st($id_st, $params);
                redirect('detail/detail_st/' . $params['id_st']);
            } else {

                $data['title'] = "Perjadin";
                $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();

                $this->load->view('template1/header', $data);
                $this->load->view('template1/sidebar');
                $this->load->view('template1/topbar');
                $this->load->view('tb_st/edit1', $data);
                $this->load->view('template1/footer');
            }
        } else
            show_error('The tb_st you are trying to edit does not exist.');
    }

    function edit2($id_st)
    {
        // check if the tb_st exists before trying to edit it
        $data['tb_st'] = $this->Tb_st_model->get_tb_st($id_st);

        if (isset($data['tb_st']['id_st'])) {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('tibadi1', 'tibadi1', 'min_length[4]');


            if ($this->form_validation->run()) {
                $params = array(
                    'id_st' => $this->input->post('id_st'),
                    'tibadi1' => $this->input->post('tibadi1'),
                    'tibadi2' => $this->input->post('tibadi2'),
                    'tibadi3' => $this->input->post('tibadi3'),
                    'dari1' => $this->input->post('dari1'),
                    'dari2' => $this->input->post('dari2'),
                    'dari3' => $this->input->post('dari3'),
                    'ke1' => $this->input->post('ke1'),
                    'ke2' => $this->input->post('ke2'),
                    'ke3' => $this->input->post('ke3'),
                    'tgl_kiri1' => $this->input->post('tgl_kiri1'),
                    'tgl_kiri2' => $this->input->post('tgl_kiri2'),
                    'tgl_kiri3' => $this->input->post('tgl_kiri3'),
                    'tgl_kanan1' => $this->input->post('tgl_kanan1'),
                    'tgl_kanan2' => $this->input->post('tgl_kanan2'),
                    'tgl_kanan3' => $this->input->post('tgl_kanan3'),
                    'kepalakiri1' => $this->input->post('kepalakiri1'),
                    'kepalakiri2' => $this->input->post('kepalakiri2'),
                    'kepalakiri3' => $this->input->post('kepalakiri3'),
                    'namakiri1' => $this->input->post('namakiri1'),
                    'namakiri2' => $this->input->post('namakiri2'),
                    'namakiri3' => $this->input->post('namakiri3'),
                    'nipkiri1' => $this->input->post('nipkiri1'),
                    'nipkiri2' => $this->input->post('nipkiri2'),
                    'nipkiri3' => $this->input->post('nipkiri3'),
                );

                $this->Tb_st_model->update_tb_st($id_st, $params);
                redirect('detail/detail_st/' . $params['id_st']);
            } else {

                $data['title'] = "Perjadin";
                $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();

                $this->load->view('template1/header', $data);
                $this->load->view('template1/sidebar');
                $this->load->view('template1/topbar');
                $this->load->view('tb_st/edit2', $data);
                $this->load->view('template1/footer');
            }
        } else
            show_error('The tb_st you are trying to edit does not exist.');
    }
}
