<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Tb_ttd extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_logged_in();

        $this->load->model('Tb_ttd_model');
    }

    /*
     * Listing of tb_ttd
     */
    function index()
    {
        $id = $this->session->userdata('id');
        $data['tb_ttd'] = $this->Tb_ttd_model->get_all_tb_ttd($id);
        $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();

        $data['title'] = "Perjadin";
        $this->load->view('template1/header', $data);
        $this->load->view('template1/sidebar');
        $this->load->view('template1/topbar');
        $this->load->view('tb_ttd/index', $data);
        $this->load->view('template1/footer');
    }

    /*
     * Adding a new tb_ttd
     */
    function add()
    {
        $this->load->library('form_validation');
        $this->form_validation->set_rules('nip_ttd', 'NIP', 'required');
        $this->form_validation->set_rules('nama_ttd', 'Nama', 'required');
        $this->form_validation->set_rules('pangkat_gol_ttd', 'Pangkat Gol', 'required');
        $this->form_validation->set_rules('jabatan_ttd', 'Jabatan', 'required');
        $this->form_validation->set_rules('kewenangan', 'Kewenangan', 'required');
        $this->form_validation->set_rules('lokasi_ttd', 'Lokasi Ttd', 'required');

        if ($this->form_validation->run()) {
            $params = array(
                'nip_ttd' => $this->input->post('nip_ttd'),
                'nama_ttd' => $this->input->post('nama_ttd'),
                'pangkat_gol_ttd' => $this->input->post('pangkat_gol_ttd'),
                'jabatan_ttd' => $this->input->post('jabatan_ttd'),
                'kewenangan' => $this->input->post('kewenangan'),
                'lokasi_ttd' => $this->input->post('lokasi_ttd'),
                'id' => $this->session->userdata('id')

            );

            $tb_ttd_id = $this->Tb_ttd_model->add_tb_ttd($params);
            redirect('tb_ttd/index');
        } else {
            $data['title'] = "Perjadin";
            $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();
            $this->load->view('template1/header', $data);
            $this->load->view('template1/sidebar');
            $this->load->view('template1/topbar');
            $this->load->view('tb_ttd/add', $data);
            $this->load->view('template1/footer');
        }
    }

    /*
     * Editing a tb_ttd
     */
    function edit($id_nip_ttd)
    {
        // check if the tb_ttd exists before trying to edit it
        $data['tb_ttd'] = $this->Tb_ttd_model->get_tb_ttd($id_nip_ttd);

        if (isset($data['tb_ttd']['id_nip_ttd'])) {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('nip_ttd', 'NIP', 'required');
            $this->form_validation->set_rules('nama_ttd', 'Nama', 'required');
            $this->form_validation->set_rules('pangkat_gol_ttd', 'Pangkat Gol', 'required');
            $this->form_validation->set_rules('jabatan_ttd', 'Jabatan', 'required');
            $this->form_validation->set_rules('kewenangan', 'Kewenangan', 'required');
            $this->form_validation->set_rules('lokasi_ttd', 'Lokasi TTd', 'required');


            if ($this->form_validation->run()) {
                $params = array(
                    'nip_ttd' => $this->input->post('nip_ttd'),
                    'nama_ttd' => $this->input->post('nama_ttd'),
                    'pangkat_gol_ttd' => $this->input->post('pangkat_gol_ttd'),
                    'jabatan_ttd' => $this->input->post('jabatan_ttd'),
                    'kewenangan' => $this->input->post('kewenangan'),
                    'lokasi_ttd' => $this->input->post('lokasi_ttd'),

                );

                $this->Tb_ttd_model->update_tb_ttd($id_nip_ttd, $params);
                redirect('tb_ttd/index');
            } else {
                $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();
                $data['title'] = "Perjadin";
                $this->load->view('template1/header', $data);
                $this->load->view('template1/sidebar');
                $this->load->view('template1/topbar');
                $this->load->view('tb_ttd/edit', $data);
                $this->load->view('template1/footer');
            }
        } else
            show_error('The tb_ttd you are trying to edit does not exist.');
    }

    /*
     * Deleting tb_ttd
     */
    function remove($id_nip_ttd)
    {
        $tb_ttd = $this->Tb_ttd_model->get_tb_ttd($id_nip_ttd);

        // check if the tb_ttd exists before trying to delete it
        if (isset($tb_ttd['id_nip_ttd'])) {
            $this->Tb_ttd_model->delete_tb_ttd($id_nip_ttd);
            redirect('tb_ttd/index');
        } else
            show_error('The tb_ttd you are trying to delete does not exist.');
    }
}
