<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Tb_instansi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get tb_instansi by id_instansi
     */
    function get_tb_instansi($id_instansi)
    {
        return $this->db->get_where('tb_instansi', array('id_instansi' => $id_instansi))->row_array();
    }

    /*
     * Get all tb_instansi
     */
    function get_all_tb_instansi($id)
    {
        $this->db->order_by('id_instansi', 'desc');
        $this->db->where('id', $id);
        $this->db->from('tb_instansi');
        $query = $this->db->get();
        return $query->result_array();
    }

    /*
     * function to add new tb_instansi
     */
    function add_tb_instansi($params)
    {
        $this->db->insert('tb_instansi', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update tb_instansi
     */
    function update_tb_instansi($id_instansi, $params)
    {
        $this->db->where('id_instansi', $id_instansi);
        return $this->db->update('tb_instansi', $params);
    }

    /*
     * function to delete tb_instansi
     */
    function delete_tb_instansi($id_instansi)
    {
        return $this->db->delete('tb_instansi', array('id_instansi' => $id_instansi));
    }
}
