<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Tb_pegawai_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get tb_pegawai by id_nip
     */
    function get_tb_pegawai($id_nip)
    {
        return $this->db->get_where('tb_pegawai', array('id_nip' => $id_nip))->row_array();
    }

    /*
     * Get all tb_pegawai
     */
    function get_all_tb_pegawai($id)
    {
        $this->db->order_by('id_nip', 'desc');
        $this->db->where('id', $id);
        $this->db->from('tb_pegawai');
        $query = $this->db->get();
        return $query->result_array();
    }


    /*
     * function to add new tb_pegawai
     */
    function add_tb_pegawai($params)
    {
        $this->db->insert('tb_pegawai', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update tb_pegawai
     */
    function update_tb_pegawai($id_nip, $params)
    {
        $this->db->where('id_nip', $id_nip);
        return $this->db->update('tb_pegawai', $params);
    }

    /*
     * function to delete tb_pegawai
     */
    function delete_tb_pegawai($id_nip)
    {
        return $this->db->delete('tb_pegawai', array('id_nip' => $id_nip));
    }
}
