<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Tb_spd_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get tb_spd by id_spd
     */
    function get_tb_spd($id_spd)
    {
        return $this->db->get_where('tb_spd', array('id_spd' => $id_spd))->row_array();
    }

    /*
     * Get all tb_spd
     */
    function get_all_tb_spd($id)
    {
        $this->db->order_by('id_spd', 'desc');
        $this->db->where('id', $id);
        $this->db->from('tb_spd');
        $query = $this->db->get();
        return $query->result_array();
    }

    /*
     * function to add new tb_spd
     */
    function add_tb_spd($params)
    {
        $this->db->insert('tb_spd', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update tb_spd
     */
    function update_tb_spd($id_spd, $params)
    {
        $this->db->where('id_spd', $id_spd);
        return $this->db->update('tb_spd', $params);
    }

    /*
     * function to delete tb_spd
     */
    function delete_tb_spd($id_spd)
    {
        return $this->db->delete('tb_spd', array('id_spd' => $id_spd));
    }
}
